# Server Configuration
server:
  address: 0.0.0.0
  port: 7500
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# The header to use when identifying API keys
auth:
  header: "X-API-Key"

# Maxmind Configuration
maxmind:
  license: "LICENSE_KEY"

# GitHub Configuration - Used to scrape a public PIA repository for their servers
github:
  bearer: "" # Your GitHub bearer token
  api-version: "2022-11-28" # The version of the GitHub API to use

# InfluxDB Configuration - Used to store metrics
influxdb:
  url: "https://influxdb.local.rainnny.club"
  token: "YOUR_TOKEN"
  org: "YOUR_ORG"
  bucket: "YOUR_BUCKET"

# Log Configuration
logging:
  file:
    path: "./logs"

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/antivpn?useCompression=true&useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true&autoReconnect=true
    username: antivpn
    password: p4$$w0rd
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: antivpn
      maximum-pool-size: 51
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-timeout: 10000
      validation-timeout: 3000
  data:
    # MongoDB - This is used to store persistent data, such as API keys.
    mongodb:
      uri: "mongodb://antivpn:p4$$w0rd@127.0.0.1:27017/antivpn?authSource=admin"
      auto-index-creation: true # Automatically create collection indexes

    # Redis - This is used for caching
    redis:
      host: "127.0.0.1"
      port: 6379
      database: 0
      auth: "" # Leave blank for no auth
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
  #        generate_statistics: true
  sql:
    init:
      mode: always
  mvc:
    application:
      ipv4only: true

  # Ignore
  application:
    name: "Rainnny's AntiVPN"
  banner:
    location: "classpath:banner.txt"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

threads: 50 # The amount of threads the thread pool should use when ticking
dev: true # Are we in a development environment?
amiusingavpn: false # Enable this route?
debug: false # Enable debug mode